export const addSubmissionsAndDownloadConstants = {
  addOpinionScale: "add-opinion-scale-element",
  addStarRating: "add-star-rating-element",
  addMatrix: "add-matrix-element",
  contentTextField: "content-text-field",
  starRatingGroup: "star-rating-preview-group",
  opinionScaleGroup: "opinion-scale-preview-group",
  publishButton: "publish-button",
  publishPreviewButton: "publish-preview-button",
  emailTextField: "email-text-field",
  opinionScale: "form-opinion-scale",
  previewRatingIcon: "preview-rating-icon",
  closePaneButton: "pane-close-button",
  submitButton: "start-or-submit-button",
  thankYouPage: "thank-you-page-content",
  submissionsTab: "submissions-tab",
  submittedResponse: "submitted-response-1",
  viewSubmissionButton: "view-submission-1-button",
  backdrop: "backdrop",
  pdfRadioLabel: "pdf-radio-label",
  actionDropdownButton: "action-dropdown-btn",
};
